on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.4
      - run: ko publish ./ --platform=all
