on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v2

      - uses: sigstore/cosign-installer@2.3.0
      - uses: imjasonh/setup-crane@v0.1
      - uses: imjasonh/setup-ko@v0.4
      - run: |
          # Publish the image and its many various SBOMs.
          img=$(ko build ./ -P --platform=all --sbom=cyclonedx)

          # Fetch each SBOM.
          crane manifest $img | \
              jq -r '.manifests[].digest' | \
              xargs -I{} cosign download sbom ghcr.io/${{ github.repository }}/github.com/imjasonh/sbom-fun@{}
